# Sensor Configuration
polling_hz: 30
sensor_name: bottom_center
connectors:
    # MPU 6050
    -   bus: 1
        address: 0x68
    # TODO: model 2
    -   bus: 1
        address: 0x71


# Calibrations
ang_vel_offset: [ 0, 0, 0 ]
accel_offset: [ 0, 0, 0 ]
temp_offset: 0
